### ISSUE TITLE
Problems with publishing a topic from a webpage.

### ISSUE THREAD

**Issue by jdtayyub** [PDuckworth/activity_analysis#1]
@marc-hanheide We are struggling to publish from a topic I created on a webpage  [here](https://github.com/PDuckworth/activity_analysis/blob/master/consent_tsc/webserver/recording.html#L35-L51). Basically, we are able to publish the topic, however as soon as the page is called again using the strands_ui webserver [here](https://github.com/PDuckworth/activity_analysis/blob/master/consent_tsc/scripts/consent_for_images.py#L42), the topic stops publishing. For some reason, re-echoing it happens to start the publishing again. Any thoughts on what might be going wrong when recalling the page.

**Comment by marc-hanheide** [comment]
I don't quite understand. So, the publishing works but when the page is reloaded it doesn't? Or does it publish regardless if a button is pressed or not? Does the browser's JavaScript console say anything?

**Comment by jdtayyub** [comment]
Yes the first one, publishing works yes, but when the page is reloaded it doesn't. JS console doesn't have any errors.

**Comment by marc-hanheide** [comment]
Not even says that it is connected to websocket on reload?
Anyway, I think you should be using a Ros service instead of a topic here. I've never used topics for communication from JavaScript to the system. A button press should be a service call, IMO.

**Comment by jdtayyub** [comment]
Sorry, I meant to say that it shows 'no errors' in the console, it does always say it is connected to the web socket. After a bit of brute force testing, we've realised there is just lag. After a reload, the messages eventually publish once clicked on a button but not as quickly as the first load of the page.

**Comment by marc-hanheide** [comment]
OK, here's what I think is going on: on reload the topic connection is interrupted, eventually it is timed out but as long as it isn't the new connection isn't established. Publishers are not meant to disappear out of the blue. So, again, you should use a service for this. That will reconnect the moment you reload and also if needed when you press the button.

**Comment by jdtayyub** [comment]
Alright, thank you for letting us know what might have been going on. I was suggesting a solution which would have one page served from the web server, and at every button press, the page content changes through JavaScript but the page never gets reloaded and thereby never having a connection interruption. Does that sound like a viable solution? Also could you let us know any example where a button has been implemented as a service on rosjslib? Thanks

**Comment by marc-hanheide** [comment]
I strongly advise using services. It's easy, but I'm on my phone the while time and not at my desk. But @cdondrup has many examples and there is even some button factory on strands_webserver itself if I'm not mistaken. You can also browse the aaf_deployment repository which contains dozen examples, e.g. as part of the walking group or the aaf_control_ui. Hope this helps

**Comment by jdtayyub** [comment]
Hi Marc, Im having a new problem now, the web socket now keeps disconnecting after receiving a message from a publishing topic. However, this only happens on Firefox and not on Chrome. Have you come across this before, if so, any ideas on what might be going on?

**Comment by marc-hanheide** [comment]
Nope never had that. Again, no error message? Where is the code? You receive one message correctly?

**Comment by jdtayyub** [comment]
Hi Marc, the issue seemed to self-resolve. Thanks for the help though :)

**Comment by PDuckworth** [comment]
I've closed because we don't publish the message from a webpage any more. Services are used.
